[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Ваше Имя"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.100"
uvicorn = "^0.23"
sqlalchemy = "^2.0"
psycopg2 = "^2.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
